server:
  # the host is api server hostname
  # is used to upload file
  host: go.cmdb.com
  # api server port
  port: 8000
  # domain is used to set token
  domain: cmdb.com
  token_exp: 600 # seconds
  default_page_num: 1
  default_page_size: 10
  websocket_update_interval: 10 # seconds


agent:
  # token to auth agent
  token: 111666
  # agent http server port to send actions message
  port: 8800


log:
  log_dir_name: logs
  log_file_name: cmdb.log


env:
  # env: dev|product
  env: dev


filesystem:
  # 8 << 20 <==> 8 MiB
  max_multipart_memory: 20
  user_static_dir_name: users
  user_static_url: /user


# front end domain
cors:
  allow_origins:
    - "http://go.cmdb.com:8888"

  ## X-Requested-With is for allowing OPTIONS method of upload file.
  allow_headers:
    - Origin
    - Authorization
    - Content-Type
    - X-Requested-With

  # Since Non-simple requests will do a preflight request (with OPTIONS method)，
  # so we should permit OPTIONS here.
  allow_methods:
    - OPTIONS
    - PUT
    - PATCH
    - POST
    - GET
    - HEAD
    - DELETE

  # Since only the following six HEADER fields could be catch by
  # getResponseHeader method of XMLHttpRequest Object while a CORS request:
  # Cache-Control、Content-Language、Content-Type、Expires、Last-Modified、Pragma.
  # Other Headers should be specified within "Access-Control-Expose-Headers" if they want be took.
  expose_headers:
    - Content-Length

  allow_credentials: true
  max_age: 12  # hours


jwt:
  max_exp: 600  # seconds


mysql:
  # database hostname
  host: mariadb-server
  port: 3306
  db_name: gocmdb
  db_user: cmdb
  db_password: 123456
  max_conn: 10
  max_idle: 5


aliyun:
  default_region_id: cn-zhangjiakou
  access_key_id: LTAI4GEBoCN3GUfd1i
  access_key_secret: n23QvMe6FkwsWcVexBEa6AFb

tencent:
  default_region_id: ap-beijing
  access_key_id: AKIDgnjRUcfMtDt24pgFbiY8TfcdegS
  access_key_secret: e3CChK2Xpt9qPR0FEze3C1h

update_host_record:
  interval: 5 # seconds

